### ISSUE TITLE
current issues (screen shots)

### ISSUE THREAD

**Issue by AndrewStoumbos** [AndrewStoumbos/3402LEXER#1]
![Screenshot 2024-10-22 174235](https://github.com/user-attachments/assets/4dc3d552-8fed-4f9d-8ed4-03d27de1f402)

![Screenshot 2024-10-22 174324](https://github.com/user-attachments/assets/000d3cc0-a85c-47aa-907d-5f4aefc315d4)

**Comment by babahaj** [comment]
shouldn'y we pass argv[1] when we call lexer_init? We are supposed to be passing the file name not the actual file.

**Comment by AndrewStoumbos** [comment]
im not sure if the file name is always going to be at place 1

**Comment by AndrewStoumbos** [comment]
ok the issue is we are passing a file pointer when It should be just a string

**Comment by babahaj** [comment]
its always going to be at index 1 because we are reading the file before hand: 

// Initialize with the input file
FILE *input_file = fopen(argv[1], "r");

argv[1] is file name and "r" means we read it.

**Comment by babahaj** [comment]
yea the issue is we are passing FILE* instead of char* and the char* should be the file name

**Comment by babahaj** [comment]
> ok the issue is we are passing a file pointer when It should be just a string

yea the issue is we are passing FILE* instead of char* and the char* should be the file name.

I changed the argument we pass to be argv[1] instead of input_file and it compiles fine. We pass all hw test cases but not all hw error test cases.

**Comment by babahaj** [comment]
> ok the issue is we are passing a file pointer when It should be just a string
